---
title: Java基础笔记：异常
author: MuMu
date: 2021-04-01 19:32:00
categories: [Java]
tags: [Java]
---

## Java中的异常

异常的分类：

![](https://blog.caowei.xyz/blog/Jbasic-3.jpg)

与异常处理有关的关键字：

+ 捕获异常：**try** / **catch** / **finally**
+ 声明异常：**throws**
+ 抛出异常：**throw**

> Java规定：
>
> 对于可查异常必须catch或者抛出
>
> 允许忽略不可查的RuntimeException(及子类)和Error(及子类)

### 捕获异常：try / catch / finally

````java
Scanner sc = new Scanner(System.in);
try {
    System.out.println("输入A");
    int a = sc.nextInt();
    System.out.println("输入B");
    int b = sc.nextInt();

    System.out.println(a/b);
} catch (InputMismatchException e) {
    System.out.println("输入整数");
} catch (ArithmeticException e) {
    System.out.println("被除不能为0");
} catch (Exception e) {
    //catch是有先后顺序的。通常在最后加上一个异常的父类，以此保证能捕获到所有异常
    e.printStackTrace();
    //强制终止程序运行
    System.exit(1);
} finally {
    System.out.println("运算结束");
}
````

当try / catch / finally三个块中都有return语句时，总会执行finally块中的return语句，以此不建议在finally块中使用return

### 声明异常：throws

*用在方法定义时声明该方法要抛出的异常类型*

由调用该方法的方法去处理异常（谁调用谁处理）

```java
public static void main(String[] args) {
    //调用testTry()方法是进行处理
    try {
        int result = testTry();
    } catch (ArithmeticException e) {
        System.out.println("Input wrong num");
    } catch (InputMismatchException e) {
        System.out.println("Input wrong type");
    }
}

//testTry()方法抛出了一个异常
public static int testTry() throws ArithmeticException, InputMismatchException {
    Scanner sc = new Scanner(System.in);

    System.out.println("输入A");
    int a = sc.nextInt();
    System.out.println("输入B");
    int b = sc.nextInt();

    return a / b;
}
```

### **抛出异常：throw**

*用来主动抛出一个异常*

只能抛出可抛出类`Throwable`或者其子类的实例对象

一般有两种处理方式：

1\. 自己抛出，自己处理

  ```java
  public static void main(String[] args) {
      throwDemo();
  }

  //限定只能输入10以下的数字
  public static int throwDemo() {
      System.out.println("输入A");
      Scanner sc = new Scanner(System.in);
      int a = sc.nextInt();

      if(a >= 10) {
          //输入大于10的数字之后，抛出异常，自己处理
          try {
              throw new Exception("只能输入10以下的数字");
          } catch (Exception e) {
              e.printStackTrace();
          }
      } else {
          System.out.println("输入正确");
      }

      return a;
  }
  ```

  输出结果：
  ![](https://blog.caowei.xyz/blog/Jbasic-1.png)

2\. 谁调用，谁处理

通过`throws`在方法中声明抛出的异常类型，由调用方法者处理或继续向上抛出

 注：`throws`可以声明与`throw`抛出对`象相同的异常类型或其父类（声明>=抛出)

  ````java
  public static void main(String[] args) {
      //由调用的方法对异常进行处理
      try {
          throwDemo();
      } catch (Exception e) {
          e.printStackTrace();
      }
  }

  //使用throws声明抛出的异常类型
  public static int throwDemo() throws Exception {
      System.out.println("输入A");
      Scanner sc = new Scanner(System.in);
      int a = sc.nextInt();

      if(a > 10) {
          //只抛出不处理，抛出异常可以是声明异常或其子类
          throw new InputMismatchException("只能输入10以下的数字");
      } else {
          System.out.println("输入正确");
      }

      return a;
  }
  ````

  输出结果：

  ![](https://blog.caowei.xyz/blog/Jbasic-2.png)

借此可以处理一些特定的业务需求。

#### 自定义异常

```java
public class WrongNumException extends Exception{
    public WrongNumException() {
        super("只能输入10以下的数字");
    }
}
```
